Repository sopt-makers/makers-design-system, pull requests merged in 2023-10, with the labels that each got.

#6 feat(makers-colors): 컬러 version 2.0.0 업데이트
  .changeset/odd-snakes-ring.md
  .changeset/wicked-candles-listen.md
  packages/colors/package.json
  packages/colors/src/colors.ts
Labels: size/M

#8 feat(colors): grayscale color 수정(2.1.0)
  .changeset/odd-snakes-ring.md
  packages/colors/CHANGELOG.md
  packages/colors/package.json
  packages/colors/src/colors.ts
Labels: size/S

#10 feat(colors): alpha 컬러 추가
  packages/colors/CHANGELOG.md
  packages/colors/package.json
  packages/colors/src/colors.ts
Labels: size/S

#13 feat: changeset release action 추가
  .github/workflows/release.yml
Labels: size/M

#14 feat(colors): mds 3.0.0 추가
  .changeset/smart-singers-wink.md
  packages/colors/src/colors.ts
Labels: size/M

#16 feat(fonts): release 1.0.0
  .changeset/bright-papayas-cough.md
  packages/fonts/package.json
  packages/fonts/src/fonts.ts
  packages/fonts/src/index.ts
  packages/fonts/tsconfig.json
Labels: size/L
