Repository sopt-makers/makers-design-system, pull requests merged in 2024-04, with the labels that each got.

#67 [DOCS] input storybook 작성
  apps/docs/package.json
  apps/docs/src/stories/SearchField.stories.tsx
  apps/docs/src/stories/Test.stories.ts
  apps/docs/src/stories/TextArea.stories.tsx
  apps/docs/src/stories/TextField.stories.tsx
  yarn.lock
Labels: size/L

#68 chore: change index path
  .changeset/breezy-pillows-help.md
  .changeset/rude-elephants-warn.md
  .changeset/smooth-dogs-begin.md
  apps/docs/.gitignore
  apps/docs/package.json
  apps/docs/src/stories/SearchField.stories.tsx
  packages/colors/index.ts
  packages/fonts/index.ts
  packages/icons/index.ts
  packages/icons/src/index.ts
  packages/icons/tsconfig.json
  yarn.lock
Labels: size/M

#72 [Icon] feat : Add IconWrite svg component
  .changeset/early-queens-decide.md
  packages/icons/src/Icon/Editor/ic-write.tsx
  packages/icons/src/Icon/Editor/index.ts
Labels: size/M

#75 [UI] feat: textarea 스크롤 추가, 엔터키로 submit
  .changeset/ten-weeks-listen.md
  apps/docs/src/App.tsx
  packages/ui/Input/SearchField.tsx
  packages/ui/Input/TextArea.tsx
  packages/ui/Input/TextField.tsx
  packages/ui/Input/style.css.ts
Labels: size/L

#79 [ICONS] fix: name, stroke
  .changeset/four-poets-grow.md
  packages/icons/src/Editor/ic-letter-spacing.tsx
  packages/icons/src/Feedback/ic-help-circle.tsx
  packages/icons/src/Feedback/ic-info-circle.tsx
  packages/icons/src/Feedback/index.ts
  packages/icons/src/Users/ic-user.tsx
Labels: size/S

#81 [DOCS] Icons, Colors storybook
  apps/docs/.storybook/main.ts
  apps/docs/package.json
  apps/docs/src/index.css
  apps/docs/src/stories/Colors.stories.tsx
  apps/docs/src/stories/Icons.stories.tsx
  yarn.lock
Labels: size/L

#82 [DOCS] Fonts storybook
  apps/docs/src/index.css
  apps/docs/src/stories/Colors.stories.tsx
  apps/docs/src/stories/Fonts.stories.tsx
Labels: size/L
