Repository sopt-makers/makers-design-system, pull requests merged in 2024-11, with the labels that each got.

#195 refactor(ui): TextField 컴포넌트, FieldBox를 사용한 형태로 리팩토링.
  .changeset/tiny-days-hammer.md
  apps/docs/src/stories/TextField.stories.tsx
  packages/ui/FieldBox/components/Label.tsx
  packages/ui/Input/TextField.tsx
Labels: size/M

#198 fix(ui): Extend HTMLDivElement in Tag Component
  .changeset/warm-hotels-march.md
  packages/ui/Tag/Tag.tsx
  packages/ui/Tag/index.tsx
  packages/ui/index.ts
Labels: size/M

#201 fix(ui): Button 내 min-width 속성 추가
  .changeset/stale-rules-rhyme.md
  packages/ui/Button/style.css.ts
Labels: size/XS

#204 fix(ui): Textarea maxLength 초과시 error 뜨도록 변경
  .changeset/shiny-dogs-hope.md
  packages/ui/Input/TextArea.tsx
Labels: size/M

#206 fix(ui): Textarea maxLength 초과시 error 뜨도록 변경
  .changeset/chatty-plants-shave.md
  packages/ui/FieldBox/components/ErrorMessage.tsx
  packages/ui/Input/TextArea.tsx
Labels: size/S

#208 chore(all): Optimize packages
  .changeset/good-flies-judge.md
  packages/colors/package.json
  packages/fonts/package.json
  packages/icons/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: size/M

#212 feat(ui) Tag 컴포넌트에 ...restProps를 추가합니다.
  .changeset/cold-owls-rule.md
  packages/ui/Tag/Tag.tsx
Labels: size/XS

#214 fix(ui): TextArea 컴포넌트 forwardRef 추가, value prop optional로 변경.
  .changeset/eight-donuts-act.md
  packages/ui/Input/TextArea.tsx
Labels: size/S

#216 fix(ui): TextArea Value prop이 undefined일 경우 발생하는 타입 에러 수정
  .changeset/pretty-eggs-teach.md
  apps/docs/src/App.tsx
  packages/ui/Input/TextArea.tsx
Labels: size/S

#218 fix(ui): Select에 createPortal 적용
  packages/ui/Input/Select.tsx
  packages/ui/Input/style.css.ts
Labels: size/M

#219 add changeset
  .changeset/five-hornets-listen.md
Labels: size/XS

#221 fix(ui): Chip에 disabled 스타일 적용
  .changeset/calm-dolphins-shave.md
  packages/ui/Chip/style.css.ts
Labels: size/S
