Repository sopt-makers/makers-design-system, pull requests merged in 2024-09, with the labels that each got.

#124 chore(ui): Vitest 초기세팅을 진행합니다.
  .gitignore
  .yarn/install-state.gz
  .yarn/releases/yarn-4.4.1.cjs
  .yarnrc.yml
  package-lock.json
  package.json
  packages/colors/package.json
  packages/eslint-config-custom/react-internal.js
  packages/fonts/package.json
  packages/ui/Test/Test.test.tsx
  packages/ui/package.json
  packages/ui/tsconfig.json
  packages/ui/vitest.config.mjs
  packages/ui/vitest.setup.ts
  turbo.json
  yarn.lock
Labels: size/XXL

#126 fix(ui): vitest lint 세팅 오류 수정
  packages/eslint-config-custom/package.json
  packages/eslint-config-custom/react-internal.js
  packages/ui/.eslintrc.js
  packages/ui/Dialog/types.ts
  turbo.json
  yarn.lock
Labels: size/L

#127 chore: pnpm으로 마이그레이션을 진행합니다.
  .changeset/giant-dolphins-beam.md
  .github/workflows/release.yml
  .gitignore
  .husky/pre-commit
  .npmrc
  .yarn/releases/yarn-4.4.1.cjs
  .yarnrc.yml
  package.json
  packages/ui/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  yarn.lock
Labels: size/XXL

#128 fix: add install pnpm workflow.
  .github/workflows/release.yml
Labels: size/XS

#130 fix: release workflow에 pnpm setup action 추가
  .github/workflows/release.yml
  package.json
Labels: size/S

#131 fix: icons 패키지 빌드 오류 해결
  .changeset/tame-boxes-tickle.md
  packages/icons/package.json
  pnpm-lock.yaml
Labels: size/M

#134 feat: 테스트를 자동화합니다.
  .github/workflows/vitest.yml
Labels: size/S

#140 feat(Button): Outlined style을 추가합니다.
  .changeset/sour-lions-notice.md
  apps/docs/src/stories/Button.stories.tsx
  packages/ui/Button/Button.tsx
  packages/ui/Button/constants.ts
  packages/ui/Button/style.css.ts
  packages/ui/Button/types.ts
  packages/ui/Button/utils.ts
Labels: size/L

#142 chore(ui, docs): 패키지 의존성 업데이트 및 docs를 최신화합니다.
  .changeset/tall-boxes-fly.md
  .changeset/wicked-donkeys-switch.md
  apps/docs/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: size/M

#145 fix(Dialog): Dialog onClick 이벤트 이슈 수정
  .changeset/slow-beers-mate.md
  packages/ui/Dialog/DialogComponent.tsx
  packages/ui/Dialog/style.css.ts
Labels: size/M

#144 feat(Select): Select를서브 컴포넌트로 분리하여 구성
  .changeset/spicy-ducks-beam.md
  packages/ui/Input/Select.tsx
  packages/ui/Input/deprecated/Select.tsx
  packages/ui/Input/index.tsx
  packages/ui/Input/style.css.ts
  packages/ui/index.ts
Labels: size/XL

#149 feat(Select): 서브 컴포넌트 사용 케이스를 나누어 스토리북 작성
  .changeset/fluffy-plants-double.md
  apps/docs/package.json
  apps/docs/src/stories/Select.stories.tsx
  apps/docs/src/stories/SelectV2NoTriggerContent.stories.tsx
  apps/docs/src/stories/SelectV2WithTriggerContent.stories.tsx
  pnpm-lock.yaml
Labels: size/XL

#152 feat(Button): 유닛 테스트 코드를 작성합니다.
  .changeset/eighty-planets-film.md
  packages/ui/Button/test/Button.test.tsx
Labels: size/M

#156 feat(Tab): 유닛 테스트 코드를 작성합니다.
  apps/docs/src/stories/Tab.stories.tsx
  packages/ui/Tab/test/Tab.test.tsx
Labels: size/M
