Repository sopt-makers/makers-design-system, pull requests merged in 2024-12, with the labels that each got.

#223 feat(FieldBox): FieldBox 컴포넌트에 TopAddon을 추가합니다.
  .changeset/violet-ducks-juggle.md
  apps/docs/src/stories/FieldBox.stories.tsx
  packages/ui/FieldBox/FieldBox.tsx
  packages/ui/FieldBox/components/Label.tsx
  packages/ui/FieldBox/components/TopAddon.tsx
  packages/ui/FieldBox/components/index.ts
  packages/ui/FieldBox/style.css.ts
  packages/ui/Input/TextField.tsx
Labels: size/L

#225 fix(Button): disabled 상태일 경우 `cursor: not-allowed` 스타일 추가
  .changeset/thick-bikes-cough.md
  packages/ui/Button/style.css.ts
Labels: size/S

#228 refactor(ui): SelectV2 TriggerContent 내 커스텀 Icon을 적용할 수 있도록 icon prop 추가.
  .changeset/early-owls-protect.md
  packages/ui/Input/Select.tsx
Labels: size/M

#230 feat(icon): currentColor 적용, Logo 및 location 추가
  .changeset/tasty-teachers-burn.md
  apps/docs/src/stories/Icons.stories.tsx
  packages/icons/index.ts
  packages/icons/src/Communication/ic-birthday-primary.tsx
  packages/icons/src/Communication/ic-birthday-secondary.tsx
  packages/icons/src/Communication/ic-location-filled.tsx
  packages/icons/src/Communication/ic-location.tsx
  packages/icons/src/Communication/ic-phone.tsx
  packages/icons/src/Communication/index.ts
  packages/icons/src/General/ic-dots-vertical.tsx
  packages/icons/src/Logo/ic-apple.tsx
  packages/icons/src/Logo/ic-behance.tsx
  packages/icons/src/Logo/ic-facebook.tsx
  packages/icons/src/Logo/ic-github.tsx
  packages/icons/src/Logo/ic-google-color.tsx
  packages/icons/src/Logo/ic-google-mono.tsx
  packages/icons/src/Logo/ic-instagram.tsx
  packages/icons/src/Logo/ic-kakao.tsx
  packages/icons/src/Logo/ic-linkedin.tsx
  packages/icons/src/Logo/ic-playstore.tsx
  packages/icons/src/Logo/index.ts
Labels: size/XL

#232 feat(ui) Tag 컴포넌트에 className prop을 추가합니다.
  .changeset/short-hats-drop.md
  apps/docs/src/stories/Tag.stories.tsx
  packages/ui/Tag/Tag.tsx
  packages/ui/Tag/utils.ts
Labels: size/M
