Repository sopt-makers/makers-design-system, pull requests merged in 2024-10, with the labels that each got.

#162 fix(colors): backgroundDimmed 컬러 피그마와 다르게 적용되어있는 부분을 수정합니다.
  .changeset/three-spiders-whisper.md
  packages/colors/src/colors.ts
Labels: size/L

#160 fix(ui): Vitest globals 옵션 사용 시 lint error가 발생하는 문제를 해결합니다.
  .changeset/many-houses-hang.md
  packages/eslint-config-custom/package.json
  packages/ui/.eslintrc.js
  packages/ui/Button/test/Button.test.tsx
  packages/ui/Control/test/Checkbox.test.tsx
  packages/ui/Control/test/Radio.test.tsx
  packages/ui/Control/test/Toggle.test.tsx
  packages/ui/Tab/test/Tab.test.tsx
  pnpm-lock.yaml
Labels: size/L

#157 refact(TextArea): 기능 개선
  .changeset/polite-oranges-speak.md
  apps/docs/src/App.tsx
  packages/ui/Input/TextArea.tsx
  packages/ui/Input/style.css.ts
Labels: enhancement, size/L

#167 refactor(Button): Button Medium 의 text size를 14px -> 16px로 변경합니다.
  .changeset/lucky-onions-hug.md
  packages/ui/Button/constants.ts
Labels: size/XS

#169 feat: ui 패키지 의존성을 업데이트합니다.
  .changeset/witty-cougars-breathe.md
  apps/docs/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: size/S

#171 chore(ui, docs): 의존성 버전 workspace:^로 변경
  .changeset/fluffy-dragons-shop.md
  apps/docs/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: size/L

#174 refactor(Select): Select padding/border 명세와 상이한 부분 수정
  .changeset/serious-beers-swim.md
  packages/ui/Input/Select.tsx
  packages/ui/Input/style.css.ts
Labels: size/M

#179 Update README.md
  README.md
Labels: size/M

#177 feat(ui): FieldBox 컴포넌트 구현
  .changeset/four-ducks-develop.md
  apps/docs/src/App.tsx
  apps/docs/src/stories/FieldBox.stories.tsx
  packages/ui/FieldBox/FieldBox.tsx
  packages/ui/FieldBox/components/BottomAddon.tsx
  packages/ui/FieldBox/components/ErrorMessage.tsx
  packages/ui/FieldBox/components/Label.tsx
  packages/ui/FieldBox/components/index.ts
  packages/ui/FieldBox/index.ts
  packages/ui/FieldBox/style.css.ts
  packages/ui/index.ts
Labels: size/L

#178 feat(ui): Skeleton 컴포넌트 구현
  .changeset/late-icons-boil.md
  apps/docs/.eslintrc.cjs
  apps/docs/eslint.config.js
  apps/docs/package.json
  apps/docs/src/stories/Skeleton.stories.tsx
  packages/ui/Skeleton/Skeleton.tsx
  packages/ui/Skeleton/constants.ts
  packages/ui/Skeleton/index.ts
  packages/ui/Skeleton/style.css.ts
  packages/ui/Skeleton/types.ts
  packages/ui/Skeleton/utils.ts
  packages/ui/index.ts
  pnpm-lock.yaml
Labels: size/XXL

#189 Revert "feat(ui): Skeleton 컴포넌트 구현 (#178)"
  apps/docs/.eslintrc.cjs
  apps/docs/eslint.config.js
  apps/docs/package.json
  apps/docs/src/stories/Skeleton.stories.tsx
  packages/ui/Skeleton/Skeleton.tsx
  packages/ui/Skeleton/constants.ts
  packages/ui/Skeleton/index.ts
  packages/ui/Skeleton/style.css.ts
  packages/ui/Skeleton/types.ts
  packages/ui/Skeleton/utils.ts
  packages/ui/index.ts
  pnpm-lock.yaml
Labels: size/XXL

#190 FIX: Skeleton 컴포넌트 재배포
  .changeset/late-icons-boil.md
  apps/docs/.eslintrc.cjs
  apps/docs/package.json
  apps/docs/src/stories/Skeleton.stories.tsx
  packages/ui/Skeleton/Skeleton.tsx
  packages/ui/Skeleton/constants.ts
  packages/ui/Skeleton/index.ts
  packages/ui/Skeleton/style.css.ts
  packages/ui/Skeleton/types.ts
  packages/ui/Skeleton/utils.ts
  packages/ui/index.ts
  pnpm-lock.yaml
Labels: size/XXL

#183 fix(Select): border 유무에 따라 size가 변형되지 않도록 수정합니다.
  .changeset/sharp-boats-accept.md
  packages/ui/Input/style.css.ts
Labels: size/XS

#193 docs: Storybook Introduction 문서 추가
  .changeset/popular-keys-share.md
  apps/docs/src/stories/Configure.mdx
Labels: size/M

#188 feat(Icon): mds, phone/birth 아이콘 추가합니다
  .changeset/eighty-flies-type.md
  apps/docs/src/stories/Icons.stories.tsx
  packages/icons/src/Communication/ic-birthday-primary.tsx
  packages/icons/src/Communication/ic-birthday-secondary.tsx
  packages/icons/src/Communication/ic-phone.tsx
  packages/icons/src/Communication/index.ts
Labels: size/XL

#186 feat(Select): 커스텀 스타일 주입할 수 있도록 className을 추가하고 Menu에 zindex 설정합니다.
  .changeset/cuddly-peaches-shake.md
  apps/docs/src/App.tsx
  packages/ui/Input/Select.tsx
  packages/ui/Input/style.css.ts
Labels: size/M
