Repository sopt-makers/makers-design-system, pull requests merged in 2025-03, with the labels that each got.

#246 docs: Code owner 추가
  .github/CODEOWNERS
  README.md
Labels: documentation, size/S

#244 fix(TextArea): inputError가 적용되었을 때 focus 스타일이 적용되지 않도록 수정
  .changeset/tender-cougars-deny.md
  packages/ui/Input/TextArea.tsx
Labels: size/XS

#247 docs: cursor rule + vscode task 세팅
  .cursor/rules/rules.mdc
  .vscode/settings.json
  .vscode/tasks.json
  package.json
  scripts/vscode.sh
Labels: documentation, size/M
